spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leavebridge?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false   # 템플릿 캐싱 비활성화 (개발 환경에서만)
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true