spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leavebridge?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none